[color]
    grid = """<script>
    const {Grid, GridItem, Pane} = window.luda;
</script>

<style>
    :global(.docs-background-color-example > div > div) {
        border: 1px black solid;
        height: 4rem;
    }
</style>

<Grid class="docs-background-color-example" ta-center>
    <GridItem span="4">
        <Pane bc-primary />
        <small>bc-primary</small>
    </GridItem>

    <GridItem span="4">
        <Pane bc-secondary />
        <small>bc-secondary</small>
    </GridItem>

    <GridItem span="4">
        <Pane bc-danger />
        <small>bc-danger</small>
    </GridItem>

    <GridItem span="4">
        <Pane bc-dark />
        <small>bc-dark</small>
    </GridItem>

    <GridItem span="4">
        <Pane bc-light />
        <small>bc-light</small>
    </GridItem>

    <GridItem span="4">
        <Pane bc-emphasis />
        <small>bc-emphasis</small>
    </GridItem>

    <GridItem span="4">
        <Pane bc-main />
        <small>bc-main</small>
    </GridItem>

    <GridItem span="4">
        <Pane bc-muted />
        <small>bc-muted</small>
    </GridItem>

    <GridItem span="4">
        <Pane bc-inverse-emphasis />
        <small>bc-inverse-emphasis</small>
    </GridItem>

    <GridItem span="4">
        <Pane bc-inverse-main />
        <small>bc-inverse-main</small>
    </GridItem>

    <GridItem span="4">
        <Pane bc-inverse-muted />
        <small>bc-inverse-muted</small>
    </GridItem>

    <GridItem span="4">
        <Pane bc-none />
        <small>bc-none *</small>
    </GridItem>
</Grid>"""

[image]
    grid = """<script>
    const {Grid, GridItem, Pane} = window.luda;
</script>

<style>
    :global(.docs-background-image-example > div > div) {
        border: 1px black solid;
        background-image: url("/assets/images/carousel-1.jpg");
        background-size: cover;
        height: 4rem;
    }
</style>

<Grid class="docs-background-image-example" ta-center>
    <GridItem span="4">
        <Pane bi-none />
        bi-none *
    </GridItem>
</Grid>"""

[position]
    grid = """<script>
    const {Grid, GridItem, Pane} = window.luda;
</script>

<style>
    :global(.docs-background-position-example > div > div) {
        border: 1px black solid;
        background-image: url("/assets/images/carousel-1.jpg");
        background-size: 4rem;
        height: 4rem;
    }
</style>

<Grid class="docs-background-position-example" ta-center>
    <GridItem span="4">
        <Pane bp-c />
        bp-c
    </GridItem>

    <GridItem span="4">
        <Pane bp-rc />
        bp-rc
    </GridItem>

    <GridItem span="4">
        <Pane bp-lc />
        bp-lc
    </GridItem>

    <GridItem span="4">
        <Pane bp-ct />
        bp-ct
    </GridItem>

    <GridItem span="4">
        <Pane bp-cb />
        bp-cb
    </GridItem>

    <GridItem span="4">
        <Pane bp-lt />
        bp-lt
    </GridItem>

    <GridItem span="4">
        <Pane bp-lb />
        bp-lb
    </GridItem>

    <GridItem span="4">
        <Pane bp-rt />
        bp-rt
    </GridItem>

    <GridItem span="4">
        <Pane bp-rb />
        bp-rb
    </GridItem>
</Grid>"""

[size]
    grid = """<script>
    const {Grid, GridItem, Pane} = window.luda;
</script>

<style>
    :global(.docs-background-size-example > div > div) {
        border: 1px black solid;
        background-image: url("/assets/images/carousel-1.jpg");
        height: 4rem;
    }
</style>

<Grid class="docs-background-size-example" ta-center>
    <GridItem span="4">
        <Pane bs-cover />
        bs-cover
    </GridItem>

    <GridItem span="4">
        <Pane bs-contain />
        bs-contain
    </GridItem>

    <GridItem span="4">
        <Pane bs-auto />
        bs-auto
    </GridItem>

    <GridItem span="4">
        <Pane bs-100-auto />
        bs-100-auto
    </GridItem>

    <GridItem span="4">
        <Pane bs-auto-100 />
        bs-auto-100
    </GridItem>
</Grid>"""