[layouts]
    vertical = """<script>
    const {Tab, TabPanes, TabPane} = window.luda;
</script>

<style>
    :global(.docs-tab-vertical-example) {
        min-height: 10rem;
    }
</style>

<Tab class="docs-tab-vertical-example">
    <TabPanes>
        <TabPane title="Tab One" active>
            <p>
                Once upon time a girl named Cinderella lived with her stepmother and two stepsisters. Poor Cinderella had to work hard all day long so the others could rest...
            </p>
        </TabPane>

        <TabPane title="Tab Two">
            <p>
                It was she who had to wake up each morning when it was still dark and cold to start the fire. It was she who cooked the meals...
            </p>
        </TabPane>

        <TabPane title="Tab Three">
            <p>
                It was she who kept the fire going. The poor girl could not stay clean, from all the ashes and cinders by the fire...
            </p>
        </TabPane>
    </TabPanes>
</Tab>"""