[events]
    click = """<script>
    const {Button} = luda;

    let click_amount = 0;

    function on_click(event) {
        event.preventDefault();

        click_amount += 1;
    }
</script>

<Button color="primary" on:click={on_click}>Increment +1</Button>

<Button color="danger" disabled hollow>{click_amount}</Button>"""

[functional]
    checkbox = """<script>
    const {Button} = luda;
</script>

<Button
    color="primary"
    id="kill-bill"
    name="example1"
    value="kill_bill"
    checkbox
    hollow
>Kill Bill</Button>

<Button
    color="primary"
    id="django"
    name="example1"
    value="django"
    checkbox
    hollow
>Django</Button>"""

    file = """<script>
    const {Button} = luda;
</script>

<Button
    color="primary"
    id="example3"
    name="example3"
    file
>Upload a file</Button>

<Button
    color="primary"
    id="example4"
    name="example4"
    file
    hollow
    multiple
>Upload files</Button>"""

    radio = """<script>
    const {Button} = luda;
</script>

<Button
    color="primary"
    id="yes"
    name="example2"
    value="yes"
    radio
    hollow
>Yes, I agree.</Button>

<Button
    color="danger"
    id="no"
    name="example2"
    value="no"
    radio
    hollow
>No, I disagree.</Button>"""

[states]
    active = """<script>
    const {Button} = luda;
</script>

<Button color="primary" active>Button</Button>

<Button
    color="primary"
    id="example5"
    name="example5"
    value="example"
    active
    checkbox
>Checkbox Button</Button>

<Button
    color="primary"
    id="example6"
    name="example6"
    value="example"
    active
    radio
>Radio Button</Button>

<Button
    color="primary"
    id="example7"
    name="example7"
    active
    file
>File Button</Button>"""

    disabled = """<script>
    const {Button} = luda;
</script>

<Button color="primary" disabled hollow>Button</Button>

<Button
    color="primary"
    id="example8"
    name="example8"
    value="example"
    checkbox
    disabled
    hollow
>Checkbox Button</Button>

<Button
    color="primary"
    id="example9"
    name="example9"
    value="example"
    disabled
    hollow
    radio
>Radio Button</Button>

<Button
    color="primary"
    id="example10"
    name="example10"
    disabled
    file
    hollow
>File Button</Button>"""

    readonly = """<script>
    const {Button} = luda;
</script>

<Button
    color="primary"
    id="example11"
    name="example11"
    value="example"
    checkbox
    hollow
    readonly
>Checkbox Button</Button>

<Button
    color="primary"
    id="example12"
    name="example12"
    value="example"
    hollow
    radio
    readonly
>Radio Button</Button>"""

[sizes]
    fluid = """<script>
    const {Button} = luda;
</script>

<Button color="primary" fluid>Solid Button</Button>
<Button color="primary" hollow fluid>Hollow Button</Button>
<Button color="primary" fluid text>Text Button</Button>

<Button
    color="primary"
    id="example21"
    name="example21"
    value="example"
    checkbox
    fluid
    hollow
>Checkbox Button</Button>

<Button
    color="primary"
    id="example22"
    name="example22"
    value="example"
    hollow
    fluid
    radio
>Radio Button</Button>

<Button
    color="primary"
    id="example23"
    name="example23"
    file
    fluid
    hollow
>File Button</Button>"""

    large = """<script>
    const {Button} = luda;
</script>

<Button color="primary" size="large">Solid Button</Button>
<Button color="primary" size="large" hollow>Hollow Button</Button>
<Button color="primary" size="large" text>Text Button</Button>

<Button
    color="primary"
    id="example18"
    name="example18"
    value="example"
    size="large"
    checkbox
    hollow
>Checkbox Button</Button>

<Button
    color="primary"
    id="example19"
    name="example19"
    value="example"
    size="large"
    hollow
    radio
>Radio Button</Button>

<Button
    color="primary"
    id="example20"
    name="example20"
    size="large"
    file
    hollow
>File Button</Button>"""

    small = """<script>
    const {Button} = luda;
</script>

<Button color="primary" size="small">Solid Button</Button>
<Button color="primary" size="small" hollow>Hollow Button</Button>
<Button color="primary" size="small" text>Text Button</Button>

<Button
    color="primary"
    id="example15"
    name="example15"
    value="example"
    size="small"
    checkbox
    hollow
>Checkbox Button</Button>

<Button
    color="primary"
    id="example16"
    name="example16"
    value="example"
    size="small"
    hollow
    radio
>Radio Button</Button>

<Button
    color="primary"
    id="example17"
    name="example17"
    size="small"
    file
    hollow
>File Button</Button>"""

[styles]
    hollow = """<script>
    const {Button} = luda;
</script>

<Button color="primary" hollow>Primary</Button>
<Button color="secondary" hollow>Secondary</Button>
<Button color="dark" hollow>Dark</Button>
<Button color="light" hollow>Light</Button>
<Button color="danger" hollow>Danger</Button>"""

    solid = """<script>
    const {Button} = luda;
</script>

<Button color="primary">Primary</Button>
<Button color="secondary">Secondary</Button>
<Button color="dark">Dark</Button>
<Button color="light">Light</Button>
<Button color="danger">Danger</Button>"""

    text = """<script>
    const {Button} = luda;
</script>

<Button color="primary" text>Primary</Button>
<Button color="secondary" text>Secondary</Button>
<Button color="dark" text>Dark</Button>
<Button color="light" text>Light</Button>
<Button color="danger" text>Danger</Button>"""

[tags]
    href = """<script>
    const {Button} = luda;
</script>

<Button
    color="primary"
    href="https://google.com"
    target="_blank"
>Goto google.com</Button>"""